import HashMap from './scripts/hashMap.js';

const test = new HashMap();
test.set('apple', 'banana');
test.set('ocean', 'mountain');
test.set('giraffe', 'elephant');
test.set('sunflower', 'raindrop');
test.set('adventure', 'mystery');
test.set('laughter', 'whisper');
test.set('firefly', 'moonlight');
test.set('coffee', 'blanket');
test.set('harmony', 'chaos');
test.set('storybook', 'melody');
test.set('cactus', 'breeze');
test.set('serenade', 'twilight');
test.set('whisker', 'harbor');
test.set('zeppelin', 'lagoon');
test.set('quasar', 'carousel');
test.set('cascade', 'paradox');
test.set('silhouette', 'whirlwind');
test.set('umbrella', 'whisper');
test.set('alchemy', 'rhapsody');
test.set('enigma', 'symphony');
test.set('jubilant', 'serendipity');
test.set('sapphire', 'whirlpool');
test.set('butterfly', 'quasar');
test.set('gondola', 'zephyr');
// test.set('quicksilver', 'hologram');
// test.set('labyrinth', 'firelight');
// test.set('cinnamon', 'whisper');
// test.set('effervescent', 'echo');
// test.set('marvel', 'boulevard');
// test.set('quasar', 'sonnet');
// test.set('equinox', 'sunset');
// test.set('velvet', 'rhapsody');
// test.set('luminous', 'enchantment');
// test.set('whisper', 'harmony');
console.log(test.buckets);
console.log(test.maxSize);
console.log(test.capacity);
console.log(test.getEntries().length);
